ensure packages that can't be upgraded are present
Error: Could not update: Execution of 'brew boxen-upgrade wget' returned
1: Error: wget-1.15_2 already installed
Wrapped exception:
Execution of 'brew boxen-upgrade wget' returned 1: Error: wget-1.15_2
already installed
Error: /Stage[main]/People::Awaxa::Applications/Package[wget]/ensure:
change from 1.15_2 to 1.15 failed: Could not update: Execution of 'brew
boxen-upgrade wget' returned 1: Error: wget-1.15_2 already installed
Error: Could not update: Execution of 'brew boxen-upgrade python3'
returned 1: Error: python3-3.4.1_1 already installed
Wrapped exception:
Execution of 'brew boxen-upgrade python3' returned 1: Error:
python3-3.4.1_1 already installed
Error: /Stage[main]/People::Awaxa::Applications/Package[python3]/ensure:
change from 3.4.1_1 to 3.4.1 failed: Could not update: Execution of
'brew boxen-upgrade python3' returned 1: Error: python3-3.4.1_1 already
installed