ensure irssi is present because upgrades are failing
Error: Could not update: Execution of 'brew boxen-upgrade irssi'
returned 1: Error: irssi-0.8.16_1 already installed
Wrapped exception:
Execution of 'brew boxen-upgrade irssi' returned 1: Error:
irssi-0.8.16_1 already installed
Error: /Stage[main]/People::Awaxa::Applications/Package[irssi]/ensure:
change from 0.8.16_1 to 0.8.16 failed: Could not update: Execution of
'brew boxen-upgrade irssi' returned 1: Error: irssi-0.8.16_1 already
installed